<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="mslwnyn" failures="1" tests="3" name="Create Account: HomePage" time="58.197" errors="0" timestamp="24 Dec 2019 03:55:47 GMT">
  <testcase classname="za.co.tshimx.fnb.testcases.BaseTest" name="@AfterTest closeBrowser" time="0.017">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at za.co.tshimx.fnb.testcases.BaseTest.closeBrowser(BaseTest.java:101)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest closeBrowser -->
  <testcase classname="za.co.tshimx.fnb.testcases.HomePageTest" name="createAccount" time="5.399"/>
  <testcase classname="za.co.tshimx.fnb.testcases.HomePageTest" name="register" time="12.057"/>
  <testcase classname="za.co.tshimx.fnb.api.APITest" name="getAPITestMethod" time="14.763">
    <failure type="java.lang.AssertionError" message="Connect to regres.in:443 [regres.in/199.191.50.185] failed: Connection refused: connect">
      <![CDATA[java.lang.AssertionError: Connect to regres.in:443 [regres.in/199.191.50.185] failed: Connection refused: connect
at za.co.tshimx.fnb.api.APITest.getAPITestMethod(APITest.java:32)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getAPITestMethod -->
</testsuite> <!-- Create Account: HomePage -->
